### ISSUE TITLE
Documentation items for 0.3.2

### ISSUE THREAD

**Issue by nrbgt** [jupyrdf/ipyforcegraph#63]
## What I am trying to do...

Clean up documentation after #58, which needs to land to unblock other things.

## How I would like to learn how to do it...

- walk through each page of https://ipyforcegraph--58.org.readthedocs.build/en/58/
  - land when #58 is squashed 
  - note fixes here

### all pages
- [x] update icon links

### per-page

- [ ] `CHANGELOG.md`
  - #62
  - Addressed in #69 
- [x] `README.md`
  - [x] update screenshots
- [x] `CONTRIBUTING.md`
  - [x] clean up title to just "Contributing"
- [x] `examples/Shapes.ipynb`
  - [x] finish up the demo controls (addressed in #69)
- [x] `reference/forces.html`
  - [x] fix some dangling "`" characters after `node`, etc. 
- [ ] `examples/Behaviors.ipynb`
  - [x] clean up `task_arrows` and `task_particles` labels (addressed in #69)
  - [ ] use fewer accordions-in-accordions
- [x] `docs/reference/base.html`
  - [x] missing `HasDimensions`, etc. so downstream inheritance links are also broken
    - [ ] fixed on #66, but could do a docs hotfix against main

## How the project might keep the docs accurate...

- maybe find some patterns that can be statically checked
  - [x] find all `xref` not inside a `link` (link check will find if a link is _broken_, but not _missing_)
- maybe add some more CLI/robot tests of notebooks
  - [x] remove old `future` notebooks that don't work anymore

**Comment by nrbgt** [comment]
Reopening as we didn't get everything: moving to next milestone.
